# Generated by Django 5.1.6 on 2026-01-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="tasks",
        ),
        migrations.AddField(
            model_name="tasks",
            name="project",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="api.projects"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="task_name",
            field=models.CharField(max_length=30),
        ),
    ]
